<html>

<head>
<title>Getting Started with R - Histograms and Box and whisker plots</title>
<link rel="stylesheet" type="text/css" href="stylesheet.css">

</head>

<body>

<table align="center" style="width:80%;">
<tr>
<td class="next"><a href="scatterplots.html">Previous</a></td>
<td class="next"><a href="index.html">Course Overview</a></td>
<td class="next"><a href="multiple_plots.html">Next</a></td>
</tr>
</table>


<br><hr class="ex1"><br>

# Histograms and Box and whisker plots 

Histograms and boxplots are two methods of displaying information about the distribution of a dataset.

The good news is that most of the commands that we have covered in the previous section on scatterplots and generic, and they can also be used when producing histograms and boxplots.

### Histograms 

We've already plotted one histogram in the previous section, so let's look again at that plot.

First, we will look at the data.

<!--begin.rcode,"histograms-1",tidy=FALSE,echo=-c(1:2)
set.seed(1337)
normal_data <- rnorm(
     100, 
     mean=0, 
     sd=1
     )

hist(
     normal_data
     )
end.rcode-->

Simple enough. But if like me, you are a little pedantic about your plots, you may also want to make some changes...

<!--begin.rcode,"histograms-2",tidy=FALSE
hist(
     normal_data,
     main = "",
     xlab = "Value",
     col="gray80",
     cex = 1.4, 
     cex.axis = 1.2, 
     cex.lab = 1.2
     )
end.rcode-->


Bear in mind that we need to make some assumptions when we draw a histogram - i.e. where to choose the break points for the bins (columns). It's usually fine to leave R to make the decision for us, but we can see the result of making changes to the break points below.

<!--begin.rcode,"histograms-3",tidy=FALSE, fig.height=20,echo=FALSE

par(mfrow=c(3,1))

for (i in c(5,25,50)) {

hist(
     normal_data,
     xlab = "Value",
     ylim=c(0,30),
     col="gray80",
     cex = 1.4, 
     cex.axis = 1.2, 
     cex.lab = 1.2,
     breaks = i,
     main = paste("breaks =",i,sep=" ")
     )

}

par(mfrow=c(1,1))
end.rcode-->


You may also at some point wish to compare two histograms by overlaying one over the other. This can be done with a few tweaks, as seen in the example below. Note that we have again had to specify the number of breaks. Hence we have made some assumptions about how to display this data.

<!--begin.rcode,"histograms-4",tidy=FALSE


set.seed(1337)

# create two normally distributed vectors of random data

data_a <- rnorm(
     100,
     mean = 0,
     sd = 2
     )

data_b <- rnorm(
     100,
     mean = 2, 
     sd = 2
     )


# Plot first graph

p1<-hist(
     data_a,
     ylim = c(0,25),
     col = rgb(1,0,0,0.5), 
     main = "",
     breaks = 10,
     xlab = "Value",
     cex = 1.4, 
     cex.axis = 1.2, 
     cex.lab = 1.2
     )

# Note that you must specify an 'alpha' of less than 1 (the fourth argument in
# the rgb command), otherwise, your two colours will be completely solid. 

# Plot second graph - note use of 'add = TRUE' to overlay onto the first plot

p2<-hist(
     data_b,
     breaks = 10,
     add = TRUE,
     col = rgb(0,0,1,0.5),
     cex = 1.4, 
     cex.axis = 1.2, 
     cex.lab = 1.2
     )


end.rcode-->

### Box and whisker plots 

Boxplots similarly display information about the distribution of data, and the have the benefit of not having to make assumptions about bin width. They are not completely free of assumptions however.

A basic boxplot is shown below. 

<!--begin.rcode,"histograms-5",tidy=FALSE, echo=-1

set.seed(1337)

boxplot_data <- rnorm(
     n = 500,
     sd = 10,
     mean = 1
     )

boxplot(
     x = boxplot_data,
     col = "aliceblue",
     cex = 1.4, 
     cex.axis = 1.2, 
     cex.lab = 1.2
     )

end.rcode-->

In this example the thick line at the centre shows the median, the top and bottom of the box shows the upper and lower quartile, whilst the 'whisker' show the upper and low adjacent values. These are the highest and lowest values within 1.5 times the interquartile range (upper - lower quartile) of the upper and lower quartile respectively. Any values beyond the adjacent values are considered 'outliers' and represented by points.

Note that this is not the only way of representing data in box and whisker plots. The other possibilities are listed here: <a href="http://en.wikipedia.org/wiki/Box_plot">http://en.wikipedia.org/wiki/Box_plot</a>. For this reason, you should always mention what your boxplot is actually showing in the caption.

#### Multiple box plots 

One of the great strengths of the boxplot, is that it allows you to plot several different data sets side by side, in a much more simple and easily comparable manner than with histograms.

<div class="ex">

### Exercise 

In the next example we will use a real dataset which you are required to download from the internet and load into R using the methods we have learnt so far.

The data are available here: <a href="https://db.tt/JEoe3mQZ">https://db.tt/JEoe3mQZ</a>

<!--read.table("https://docs.google.com/spreadsheet/pub?hl=en&hl=en&key=0AjOX9_-v82CydHNneXg0WHZ6ZnZZU2FZTHgxdndKUEE&single=true&gid=0&output=csv",sep=",",header=T)//-->
Save this file to your desktop and import it to R, so that R recognises the column headings. Call the new variable <tt>car_prices</tt>.
</div>

This data compares the asking two prices of two cars: one diesel, and one petrol, from 216 car adverts. In the following example we will produce boxplots which compare the asking prices. We need to use the <tt>split()</tt> command for this.

The <tt>split()</tt> command literally splits a dataset according to a particular categorical variable.

<!--begin.rcode,"histograms-6",tidy=FALSE,echo=-1,message=FALSE,warning=FALSE
car_prices <- read.table("discount.csv",sep=",",header=T)

# Check the data

str(
     car_prices
     )

# Split it according to fuel type - note the $ operator - this is required in this case

split(
     car_prices$price,
     car_prices$fuel
     )

# This can simply be wrapped by a call to the boxplot() function

boxplot(
     split(
          car_prices$price,
          car_prices$fuel
          ),
     col = c("#66C2A5","#FC8D62")
     )

end.rcode-->

We can make additional splits to this dataset if we like, by using a <tt>list</tt> of factors to split the data by.

<!--begin.rcode,"histograms-8",tidy=FALSE,message=FALSE,warning=FALSE


boxplot(
     split(
          car_prices$price,
          list(
               car_prices$fuel,
               car_prices$type
               )
          ),
     col = c("#66C2A5","#FC8D62"),
     ylab=bquote(Asking~Price~("£")) 
     )

# Using bquote() is required here to display the £ sign correctly

end.rcode-->

<div class="ex">

### Exercise 

Using the methods above, produce a <tt>boxplot</tt> of the <tt>car_prices</tt> data, splitting teh data by seller <tt>type</tt>

</div>

<br><hr class="ex1"><br>

<table align="center" style="width:80%;">
<tr>
<td class="next"><a href="scatterplots.html">Previous</a></td>
<td class="next"><a href="index.html">Course Overview</a></td>
<td class="next"><a href="multiple_plots.html">Next</a></td>
</tr>
</table>



</body>

</html>
